# This rule is not used by the project automutate itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to automutate.snosr.se.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: automutate
    app.kubernetes.io/managed-by: kustomize
  name: autopodmanager-viewer-role
rules:
- apiGroups:
  - automutate.snosr.se.my.domain
  resources:
  - autopodmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - automutate.snosr.se.my.domain
  resources:
  - autopodmanagers/status
  verbs:
  - get
