# This rule is not used by the project automutate itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the automutate.snosr.se.my.domain.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: automutate
    app.kubernetes.io/managed-by: kustomize
  name: autopodmanager-editor-role
rules:
- apiGroups:
  - automutate.snosr.se.my.domain
  resources:
  - autopodmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automutate.snosr.se.my.domain
  resources:
  - autopodmanagers/status
  verbs:
  - get
