# This rule is not used by the project automutate itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over automutate.snosr.se.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: automutate
    app.kubernetes.io/managed-by: kustomize
  name: autopodmanager-admin-role
rules:
- apiGroups:
  - automutate.snosr.se.my.domain
  resources:
  - autopodmanagers
  verbs:
  - '*'
- apiGroups:
  - automutate.snosr.se.my.domain
  resources:
  - autopodmanagers/status
  verbs:
  - get
